apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: velero-s3-creds
    namespace: velero
data:
    cloud: ENC[AES256_GCM,data:U/FbmL64kxOP3bE4cK5s0sOxRL2dEBo4xPlpwjRn+ouZmFUJoFR1aszuA3GPhPwmkVoxYZgrHE5jXuiSf4jxe8yJgutA7IYKAGPG3dy1vfTO2/Pyxh70j5Ss1b8bqnxbdefRpd7dKzvGgPnrYyDojsVvWQbhXw5tlbZE6y3MYeb1rZyuHbKwoE4eStP7qtWTmxqvqgaWAgc=,iv:UtNgp3rwe2ySkfeMQdSHu0UCI9ykkH+M8TNQhB0qMbY=,tag:DJpSWSO3FEPmpfcGKHgrQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ2t6MDNOUUtIN2EvVzBj
            cmhqU0JTVldlM3JPMllpTjBhL2JRclNnR1RZClNKQTdybXAycUF4WFFML0xFbERO
            bVB0N3NPNEJ4T0huaHhSV3h1VEhHWE0KLS0tIDYvRWZ0ckw2aU1ORXQxMmJyN3FQ
            UTU1VmNrK3NrUUtvWWRYSEhDdDRSQWcKOixHDzVTZzRrurqRYkQplQYLDT7kHl/9
            w0CvZaNQcXHuwDT0PXPJSYp0j1U7T+clM3LO3zOgVsVTxhgIr/sS4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T12:45:57Z"
    mac: ENC[AES256_GCM,data:ulCXVpWDuTDi0dXw6ysmkSLzEJ4TpuMHf1sQmdU8xzx+bKxQQrw2XQE740oSR3xOjCMlqgAhptrmv/ZVgw3VY4St2GOE38QAwKeuDVksM6pwanR8t2A7ISlmguZVi03ehR7masYNOi6LBj4gSb9hNc1LekFBMIUU2sk8vDtwfik=,iv:2a6bVNFcIosgxl0HG1x1gho/Z+xUPlDrL/fHU1nYOcE=,tag:P7ulojeY/1A0hAIJgmZbWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
