apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: velero-s3-creds
    namespace: velero
data:
    cloud: ENC[AES256_GCM,data:8u0MWEa5VrrqHd2kqrV29Sy/SEjMmCYfxNkZyRNJe4Z9EkQlVCl0yp5wv2TRGW2na4Z7fcFJkuUfr2cFKjXCUH30CNG1JprVaOUgDhuTeulTl0qFHXKzcx4QwcMM3LjdufRL0Be83102SzYsjsUS/KE1+LrzBKy3ucQiLFf06vh9FYFBxslpZPqCxYqPItCRy6nxJ+yVaBA=,iv:p/47rhb4JWKVHP7PT4oqhfGHhIVCK6GSNsCM4pcTVyM=,tag:zZcmeJZV0D9SjBBYb0KENw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTWtaSkNHT05GM096RVlB
            aUlKc3grZUlOUWdyVzBFZTY0K3RQSXFvNW5RCnBreEd4cUhveEo5aEFiNUhXU2FE
            a2FIWUFqTVZlRzdVdGU1VXJQOHRnbEkKLS0tIFRSYW5SemU1N25nWGw0N2p3YzhG
            aDZxRjhFeDNLbnA0RVBJanVqMHB2Z2sK4smnKaTMVL77Pb+g1l8J0qzzkSxa23+G
            fVYI8mCauXc8TTDcMAwi9DxTAqllIZ0YwCN1e23QQanpdicjje3DDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T12:32:48Z"
    mac: ENC[AES256_GCM,data:h0sHnfS9lPcNY4i4Kpi6S4DLoEPr5Bi+xOqipGfueXursAjgddsGtnS1r5Gwvh4pEIq6wB9JorI8AqT0N3B1Y64UyHFEgHEuZbTIceA3XQpY0O83De7OewhfGyDPo4XoD68mLOwDe15UgqFOEempfpC2vX4TQToMNpfdzm8jJcs=,iv:b8fatAsmtSOPxS/9EVG2/DiOm7IT3OlrBATPAye0pWQ=,tag:ARYM/MaWRMBlCVpvwx0XUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
