kind: ENC[AES256_GCM,data:E30p+Q/b,iv:Top1GDT9LddE9UEgZqjVtyDBxnpVpoO2LpKoAYQzQHs=,tag:TEVXvbzFqwo3OJIOEuVAaA==,type:str]
ansible_user: ENC[AES256_GCM,data:EfSUOA==,iv:ZLJFW58DICfWcejaZ3c3o8l1xSdDRprKiXnYUDYIJp8=,tag:gLJmuUlBBAjXNuEUDhLtkQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/Azt4Zz6,iv:yeHAAHpmV5gIa0EZmzz4dcgqB/cFaMRFjJGtUV4Pg2g=,tag:qBtuVIOiqYBaonG8mftSqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S2l2b1pwaGFOVzlOMEV2
            NitBZ0NFVzhhcitETnZRb3JNdk00WnF3bFRrCmR2eHFpcmFLYlp2NFJidTRTbW5T
            dlhwZFFmcmFSSGh6eTBvd2NJTEE5d1EKLS0tIHlmdUh6ZGYvWGlQWjhnQXpIUjRh
            VyswSHBnMkY5bGlJTHZyaTVQcCtpeFUKow4Ol2kYRN27Yk/2JPKhyUSYomo/sIFF
            PS+OyKnmzEgEl0Vt/2N6QhpK04Qw+dCXVPnaddZsNGi+yjDqxPQcEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T12:45:57Z"
    mac: ENC[AES256_GCM,data:ZmR24NHit1a+ja/wYPtA1IBfjup4v7miU1UdUWpHs3NFcUjKGnHZs4w5boxkUvyeftsm/5meu9PL6l+sUnmTmVtiN+G43fOiRh+BgjFSr710hFvZpCMPMlbDhX208/eXYOftdHNhnRf9lFEYdcbKeu+otgt5s/JP00cuNUKzIhQ=,iv:+/a4TYDLuSWzDOmlQWuF60jPK/VHiGYk1yVIVB6AZA4=,tag:tm5ene870z5eM0EOAjGfMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
