kind: ENC[AES256_GCM,data:SePFOhUY,iv:MIK2bSga3RpfhF4pL2nE0IyeQtqQegR9Yp+t3/esJZQ=,tag:m9S2sjIxuWjpCiVhMIOw0A==,type:str]
ansible_user: ENC[AES256_GCM,data:wFdsZw==,iv:oMe8t8ENw+sFZ9tKWaNfRMmG59aPnEmseEUb3HQ8s/Y=,tag:SlR2est3TKMWvvmLfSIcwQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1it0y7o6iik=,iv:kiWOD0q//AVScSEYUzWK+GRQnr0nnkxSxtUjwX2d8AA=,tag:1P9fZ4B9om0cSTYppCrxaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOXFtSVI5WHppaXc5SUUy
            SjZMMzhEMjNqK0prZVVCaFBtTUNYTlpycER3CisyTmJOU0JTWDN6YVUzc2sveXNV
            cmdmL1IwNWRCSHRMUFhnaGpqem9KOUEKLS0tIEpsMUpCdFZCdzRwMk01Ym5nZDVt
            d1dtWExwSlBFYmZ1ZVVXMXNhTExrZE0KaAt/AtCTlqcMi/99IXIGh8L4NNNpBRDq
            PwYuMDQjW7M7dXPW/E9KI1JAcbBfOJkJdOXiL2U/ZL6NJsny0Y23rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T12:45:57Z"
    mac: ENC[AES256_GCM,data:xwz9avkxomP+etUCkMHHiYGx05J24zcZIFrV8INKnUCjraOl4yj3iFA/UC76mVuA2v9ulCRfMiOJy+DLy88wu5clrFvg3VIy2sPQgUSVd1rPBOLhQF4hPMH3LFt8dDO9vVAfeG6fRSDdkKuaRWSrHkJzEXaUNoAdd1iuLIY1fXE=,iv:Ne5UupiybfzPeS5TvnnhLOKU2LJoS/ITIelyqtbr9lA=,tag:3IfAikmwytB7jGgkiCz/1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
