kind: ENC[AES256_GCM,data:sD1a5oqQ,iv:bXwY9PNTFKlFg68m5612o8YrFpnx+Ug9M+aFdU3nf8o=,tag:ft/+xMZuWIC9rB8kQ85j1A==,type:str]
ansible_user: ENC[AES256_GCM,data:A5KF3w==,iv:Og85pb5FfpfAa491jsivpNjmh000Li6vntJ2UcROhLc=,tag:ZYLUU3JRt0/Mixa6cOxx5g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cQhxq1FouIw=,iv:g5rqRsbs7U4DX8yQ92Rnad2svWeOf332rAsFu849oXQ=,tag:ocUBx7jDBHKLq7hf9y1ULQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ2h0TFRUZ0NFMk1uMXRQ
            dnRyQlZBaWZqVEFMTFA3Z0dSSFNCMFJXbjBVCnhqSzI2eG9nMWN1NDFFbTgzR2hJ
            OThZMWtzR1k1a0ZNT0I3Ni9ReE0yNlkKLS0tIFNnRFVVdzlSb0JEb2VpT2ZDTnRW
            dWZwcHFlOE5rUTdJOVMvZFNOMTExNkkKJ2yDLDFIgvuk56Gg45Js459Gdt4HxLUD
            j52JpUWhP0S4UlLTq0Eo/8qqa+G4pf4WpJnC2R5of/6xjrVjLOUR8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T12:32:48Z"
    mac: ENC[AES256_GCM,data:bsmbenWUjf5QakgfRI9toqZENZSHmC7lc6g0zh1FYyMgHOpopEMU1JsfMQ0dUfmwxFtyFWFgLsLeHmcEABtqZzT7aFK62RtlZhpiQHpHimHQ0NX1Lb/a2918iu64eNxnIuKGot8GKcq26p0xlBpx/0zanI6gmXjZ95pIpFcgtfI=,iv:LJPqdr4y05NUKezRYyI9nWPl6FlLR+1XumkbfVlq5lk=,tag:NFQIrCyGOdPtEMv/8AIADA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
