apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:WMem4M3zNDExQ8nSy2LeRJwB5e2FPe25NAKem1NLgrw4BQnou2Ej/EcDtrIpjR7jIXwg4YeO3yeXPHhT,iv:9K0HmEevSL2zfHSyii39s1Wc6Vw/Mz+dE0XsUR+ZnDY=,tag:gO+KYlZXzdt9ZYDsel+v3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVVUxQ2hTcWEvMDJ0UXJX
            S1VQTm1tZVY3aUVuZWhzRjF1OEpmQis5bUhRCm4wRExGRG1mRHpUM2pGb2hQMTM0
            VWxSYnRXTjlkSXBxQVEyeitOaEV3ZkUKLS0tIGxyZFRKaGdCcURkUDBvemhzUm4v
            TkRSb0NTQUNZMnBYY1pjSUZGT1dvb0EKJMpiY9HfjLI5P9CNIHCex6in/Sb95Erl
            lNT2oc5cDRwdMByxiJvHSbEYmtDbbsHj9LJJOglX763XDTvt/vqtlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T16:03:51Z"
    mac: ENC[AES256_GCM,data:oRPQQYn4OwkGn+15txG6VREHqNaOq0h5nnLt0U78Tt821x8zuom3PRWbOlfTM6EezOkqPlFVHyQ9zOZUEVNvsHaggjij2T7VTpBvwZ6rCQDdkd6jlgPufkdfEVe/9pNRHZlruhEIIJSfvrIysipKQuJcpxjF+u5LXX/uOpeZIAY=,iv:m6V7fXOOrgjtE4sA3K3EeiKrG6oSlEfPsucx0BcNaZk=,tag:CiiPM563bHJ20j33wHpBvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
