apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
data:
    tunnel.json: ENC[AES256_GCM,data:2gv+nk7+XOGccYebobtMz9ZbnLvYL6KVyFvrStbBXI7PNJFuwxfupnte+cXjhgWL56POcoSYj4mjmNhg49a3uDOjWYCymC0s4JUrluosneDiEhfN94JwXONuMskeTmrX2Dur6KXIj0x2VJ1ZHjq3mdwGz0Sh5990+hF+pqrgI7CaM6n6gkVEgcYdrdjlq09u0CW5vtb6rSjBNSJljLCyvVgIq7ET/U83j5Z9EU94VDlIglrmldfKipCN61rzW45NUU8n2H+9RmFDJax4YJgtwclG5uFVN2H9,iv:7XoxJE1+lbG7f9nn0FNqbikX83XgGn7RDJYpkrdFGts=,tag:Vfxw8DIJ0e1XPYNc/9ChTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOXVnZjJBR2Qra2ZENUti
            SzRNZ2xtNlhyaXBYdkwvVHBBYVgwb1ZEbDJ3CjlLQXB5aTVwMnNXZFJucmRYbytn
            YWg4ZDNLVTgrNWQ3Z3c4ekZHME5CcHMKLS0tIHJIa3NPWXlsOXZoeXdGZ3JtL2RB
            Mk9TYjBPVWtNM0VkU1JGVjFrMGVQSjAK0kXjzgvbXKD5g1UtWIhBMh8br6jhmsT5
            57SW3BguqXmy6crm5ZtwN2h2xKh+6IlNE13+zVp9XTr88X92NPb0ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T12:45:57Z"
    mac: ENC[AES256_GCM,data:3otLQ2/ZB9gYJHSVJoCdKGC4ZnVsKzUdq7UwE1Vwq0Qv2YwHEYB/FRySovEjmAUBCnnAYIJjJOJ8ADQOaLeKWAjyy04C+DdU098keUKLkGy7aP4rKwraufT5t/RFjKJXOJJyOzFyodkZ3tXiN81boDwl/MfUIhkQ9SEyI/dmBEs=,iv:8o48J3hEf2bXXJRjEBuV/J+isPtNAgxxSzCKAf9BSso=,tag:2xZcUb45yUXzuuvChoz+Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
