apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
data:
    tunnel.json: ENC[AES256_GCM,data:bRsMnRw9MOq6EipDrWYVel7kihluca071d/jQLEra7om3wH3bdietT3S5DHwjA2QYOb4HuB4Pt42ruEPBr2qGxhdD+Agnbo3BWIf++HJ6OhwyZhWpl3jc4pcBdK6v0Et71NP8ZbGDtG+lgqgL/zwsBpOSVpqLtlahxUSHWbfbUIqhMO9BH0ML3ur5VvJXYPwNjRxmkpopIzyCYR8Uym6wSGZyip6W4RCpe8N4KwMcIEW9JfZ5geF9MHkS+T6XK2vhz9iQESgyOkAqRYtuIa5BAHotOlUYpfy,iv:xkzkF3KvzgIzgybSmc/RVa+2bP/LSUfqwaYkQGGFAO8=,tag:nbHd3PLSVHbwdRQXi5sBww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN1pQRXRveDE0d2dFS0xT
            VWNYTWtSbmFIakZUT1JGbWFldDlTTlE1aGlRCjJvQlFPM1dRemVYd2J1ZzB5SlE4
            dFA0aGI5VG5NcGp6aUd5VGZKV0UrenMKLS0tIHFtSXVjaHg2Q09wL3NGd05aNjlU
            TFpEa25qQTRkU01IZFZUVVZtZzBiR1kKWoG+qMFU7NJxMQ+W7C9MyIn0jGS3UTAn
            Dohxqsj05vVwL44tGl6uIpfGdS5tQbC83+Pf4Nt3cUwrbOpptUVr+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T11:21:51Z"
    mac: ENC[AES256_GCM,data:ux9lNxSnhN9NtRXNhJ7DjniSLzJ8Tpa2Zy8BwoOLGDMEPtKuALrXkqGuQmpr6eZX3kyk47Fgx/WuRiTk8XzySq4IJtq+g7kHvsOzynOmJHDtA4Lb3drpckrpBbOsINdAXjmFgmeMHNHKB9W2XPaeyM4ZC2Phm4NQ6swBj5r/c2M=,iv:I2ySvNiayeDeJiSwGJ4Q4CBubL/42Dzq0q+bt4lEqkU=,tag:/3jne7qEf5twjJ7iWGaOGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
