---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
spec:
  interval: 5m
  chart:
    spec:
      chart: emqx-operator
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: metallb
      namespace: networking
    - name: longhorn
      namespace: longhorn-system
  values:
    skipCRDs: false
    replicaCount: 1
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 30Mi
