apiVersion: v1
kind: Secret
metadata:
    name: emqx-config
    namespace: home
type: Opaque
stringData:
    dashboard_user: ENC[AES256_GCM,data:McoCFUY=,iv:tLJBIbz3SUlE6pUeSVQabkCVuubBhfqXpVIRdz/jWso=,tag:jn3KnOnP2lKmO+wVqIAKCw==,type:str]
    dashboard_password: ENC[AES256_GCM,data:B6yVPO2RWuzD,iv:T5usdEojikP7TFzDGwP3ODsdlCkFBPaBFMNVJk299/w=,tag:dODarPZ9rQILmfpuQXVdtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRUlGTE1vTWVrOEdFQlU0
            YW9mZ3pLY0UvemJmTjR4ZVZjM1JiNGQwM0hNClRoM3pxSlpJRWlQNWgzNHB1SUJN
            dE1MR2FzeThTMUlVNStPL1IwYW1yWHMKLS0tIGY0eVdoVTBDY2lINlJaR1lDREVB
            NHRvR1BZRUtmNnJPTUxKd2lQNEEwUjQKEA1bmYDCeOavWLD1m1iFmBSQi7D9n7I5
            MkgYZ5R5jyFVYxOANillgo71FygQ/5Cjv5r03PqXXifR0fmdems8QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T11:21:51Z"
    mac: ENC[AES256_GCM,data:eGg7rdsBqSTMKdGbyreioOUGAWhBf/CzH5FBBWLKRvA9MNUcoRwXPqwvtgyslAbX3NpNKudcmH8MFuK8PR+entIs/4R1wmjnYT52u7Yp5HWkVYgwFvfWx9qmIJIhyKxl3KEnJUvZGyQzZmJYiV1PJIOQsD2wXoGB/cvuRfWbDXk=,iv:B7N5dg2g1tqGWnLY94v8QjR1WuM87Yx1ryK10+6EyaM=,tag:mFUw+iu1Ai/bFgvpoVK+8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
